
#######################################################################################################################
#   ____           _                    _                             _       _                                
#  / ___|   __ _  | |_    __ _   _ __  (_)  _ __     __ _      __ _  | |_    | |__     ___    _ __ ___     ___ 
# | |      / _` | | __|  / _` | | '__| | | | '_ \   / _` |    / _` | | __|   | '_ \   / _ \  | '_ ` _ \   / _ \
# | |___  | (_| | | |_  | (_| | | |    | | | | | | | (_| |   | (_| | | |_    | | | | | (_) | | | | | | | |  __/
#  \____|  \__,_|  \__|  \__,_| |_|    |_| |_| |_|  \__,_|    \__,_|  \__|   |_| |_|  \___/  |_| |_| |_|  \___|
#                                                                                                              
#######################################################################################################################

- alias: 'Catarina em casa'
  condition:
    condition: and
    conditions:
     - condition: time
       after: '17:30:00'
       before: '19:00:00'
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
     - condition: state
       entity_id: input_boolean.notify_catarina_home
       state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.catarina
      from: 'not_home'
      to: 'home'
  action:
    - service: notify.pushbullet
      data:
        message: 'A Catarina chegou a casa'
        target:
          - email/fernando.pereira.ano@gmail.com
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Catarina chegou a casa enviado para Fernando'

        
#######################################################################################################################
#  _____                  _          _                      ____                 _   
# | ____| __  __  _ __   (_)  _ __  (_)  _ __     __ _     / ___|   ___   _ __  | |_ 
# |  _|   \ \/ / | '_ \  | | | '__| | | | '_ \   / _` |   | |      / _ \ | '__| | __|
# | |___   >  <  | |_) | | | | |    | | | | | | | (_| |   | |___  |  __/ | |    | |_ 
# |_____| /_/\_\ | .__/  |_| |_|    |_| |_| |_|  \__, |    \____|  \___| |_|     \__|
#                |_|                             |___/                               
#                
#######################################################################################################################
- alias: 'Certificado SSL a expirar'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 10
  action:
    - service: notify.pushbullet
      data:
        message: 'Aviso - O certificado expira em 10 dias' 
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Certificado expira em 10 dias'  
        
#######################################################################################################################
#  ____    ____    _         ____                                   
# / ___|  / ___|  | |       |  _ \    ___   _ __     ___  __      __
# \___ \  \___ \  | |       | |_) |  / _ \ | '_ \   / _ \ \ \ /\ / /
#  ___) |  ___) | | |___    |  _ <  |  __/ | | | | |  __/  \ V  V / 
# |____/  |____/  |_____|   |_| \_\  \___| |_| |_|  \___|   \_/\_/  
#                                                                   
#######################################################################################################################        
- alias: 'Auto Renew SSL Cert'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
  action:
    - service: shell_command.renew_ssl
    - service: notify.pushbullet
      data:
        message: 'Certificado renovado automaticamente' 
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Certificado renovado automaticamente'  
    
#######################################################################################################################
#  _   _      _        _____                              _           _          
# | | | |    / \      |_   _|   ___   _ __ ___    _ __   | |   __ _  | |_    ___ 
# | |_| |   / _ \       | |    / _ \ | '_ ` _ \  | '_ \  | |  / _` | | __|  / _ \
# |  _  |  / ___ \      | |   |  __/ | | | | | | | |_) | | | | (_| | | |_  |  __/
# |_| |_| /_/   \_\     |_|    \___| |_| |_| |_| | .__/  |_|  \__,_|  \__|  \___|
#                                                |_|                             
#######################################################################################################################

- alias: switch_ha_template
  id: switch_ha_template
  trigger:
    - platform: state
      entity_id: input_select.homeassistant_template
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.homeassistant_template.state }}"

  # IF: { sun.sun goes under horizon } THEN: { set theme to night mode }
- alias: day_to_night_theme
  id: day_to_night_theme
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homeassistant_template
        option: 'darkred'

  # IF: { sun.sun is up } THEN: { set theme to day mode }
- alias: night_to_day_theme
  id: night_to_day_theme
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homeassistant_template
        option: 'darkorange'

#######################################################################################################################                            
#  _                         _                             _ 
# | |       ___     __ _    | |       ___  __   __   ___  | |
# | |      / _ \   / _` |   | |      / _ \ \ \ / /  / _ \ | |
# | |___  | (_) | | (_| |   | |___  |  __/  \ V /  |  __/ | |
# |_____|  \___/   \__, |   |_____|  \___|   \_/    \___| |_|
#                  |___/                                     
#######################################################################################################################                                              

- id: change_Log_Lv
  alias: change Log Lv
  initial_state: 'on'  
  trigger:
    - platform: state
      entity_id: input_select.log_level
  action:
    - service: logger.set_level
      data: {}
      data_template:
        homeassistant.components: '{{ trigger.to_state.state }}'
        

#######################################################################################################################      
#   ____                  _                                                                                    
#  / ___|   __ _   _ __  | |__     __ _    __ _    ___     _ __ ___     ___   ___   ___    __ _    __ _    ___ 
# | |  _   / _` | | '__| | '_ \   / _` |  / _` |  / _ \   | '_ ` _ \   / _ \ / __| / __|  / _` |  / _` |  / _ \
# | |_| | | (_| | | |    | |_) | | (_| | | (_| | |  __/   | | | | | | |  __/ \__ \ \__ \ | (_| | | (_| | |  __/
#  \____|  \__,_| |_|    |_.__/   \__,_|  \__, |  \___|   |_| |_| |_|  \___| |___/ |___/  \__,_|  \__, |  \___|
#                                         |___/                                                   |___/        
#######################################################################################################################  
- id: garbage_message
  alias: 'Levar lixo para a rua'
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: input_boolean.notify_garbage_message
        state: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Levar o lixo para a rua"
        message: "Levar o lixo para a rua - amanhã passa o camião do lixo"
        target:
          - email/fernando.pereira.ano@gmail.com
          - email/ccaattaarriinnaa@gmail.com
    - service: script.notify_save_to_file
      data:
        message: '{{ as_timestamp (now()) | timestamp_custom("%d/%b/%Y %T") }} - Enviada mensagem para Fernando e Catarina para levar o lixo para a rua'
    - service: notify.ios_ipad_de_fernando
      data:
        message: 'Levar o lixo para a rua - amanhã passa o camião do lixo'
    - service: persistent_notification.create
      data:
        message: "Levar o lixo para a rua - amanhã passa o camião do lixo"
        title: "Levar o lixo para a rua"        
    