
#######################################################################################################################
#   ____           _                    _                             _       _                                
#  / ___|   __ _  | |_    __ _   _ __  (_)  _ __     __ _      __ _  | |_    | |__     ___    _ __ ___     ___ 
# | |      / _` | | __|  / _` | | '__| | | | '_ \   / _` |    / _` | | __|   | '_ \   / _ \  | '_ ` _ \   / _ \
# | |___  | (_| | | |_  | (_| | | |    | | | | | | | (_| |   | (_| | | |_    | | | | | (_) | | | | | | | |  __/
#  \____|  \__,_|  \__|  \__,_| |_|    |_| |_| |_|  \__,_|    \__,_|  \__|   |_| |_|  \___/  |_| |_| |_|  \___|
#                                                                                                              
#######################################################################################################################

- alias: 'Catarina em casa'
  condition:
    condition: and
    conditions:
     - condition: time
       after: '17:30:00'
       before: '19:00:00'
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
  trigger:
    platform: state
    entity_id: device_tracker.catarina
    from: 'not_home'
    to: 'home'
  action:
    service: notify.pushbullet
    data:
      message: 'A Catarina chegou a casa'
      target:
        - email/fernando.pereira.ano@gmail.com

#######################################################################################################################
#  _   _   _           _         _                                                      _                               
# | | | | (_)   __ _  | |__     | |_    ___   _ __ ___    _ __     ___   _ __    __ _  | |_   _   _   _ __    ___   ___ 
# | |_| | | |  / _` | | '_ \    | __|  / _ \ | '_ ` _ \  | '_ \   / _ \ | '__|  / _` | | __| | | | | | '__|  / _ \ / __|
# |  _  | | | | (_| | | | | |   | |_  |  __/ | | | | | | | |_) | |  __/ | |    | (_| | | |_  | |_| | | |    |  __/ \__ \
# |_| |_| |_|  \__, | |_| |_|    \__|  \___| |_| |_| |_| | .__/   \___| |_|     \__,_|  \__|  \__,_| |_|     \___| |___/
#              |___/                                     |_|                                                                    
#
#######################################################################################################################

- alias: 'Temperatura alta piso 1'
  trigger:
    platform: numeric_state
    entity_id: sensor.piso_1_temperature
    above: 26
  action:
    service: notify.pushbullet
    data_template:
        title: "Temperatura no piso 1 elevada"
        message: "A temperatura no piso 1 é {{ states.sensor.piso_1_temperature.state }} graus"
        target:
            - email/fernando.pereira.ano@gmail.com
            - email/ccaattaarriinnaa@gmail.com
      
      
- alias: 'Temperatura alta piso 0'
  trigger:
    platform: numeric_state
    entity_id: sensor.piso_0_temperature
    above: 25
  action:
    service: notify.pushbullet
    data_template:
        title: "Temperatura no piso 0 elevada"
        message: "A temperatura no piso 0 é {{ states.sensor.piso_0_temperature.state }} graus"
        target:
            - email/fernando.pereira.ano@gmail.com
            - email/ccaattaarriinnaa@gmail.com
        
        
#######################################################################################################################
#  _____                  _          _                      ____                 _   
# | ____| __  __  _ __   (_)  _ __  (_)  _ __     __ _     / ___|   ___   _ __  | |_ 
# |  _|   \ \/ / | '_ \  | | | '__| | | | '_ \   / _` |   | |      / _ \ | '__| | __|
# | |___   >  <  | |_) | | | | |    | | | | | | | (_| |   | |___  |  __/ | |    | |_ 
# |_____| /_/\_\ | .__/  |_| |_|    |_| |_| |_|  \__, |    \____|  \___| |_|     \__|
#                |_|                             |___/                               
#                
#######################################################################################################################
- alias: 'Certificado SSL a expirar'
  trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 10
  action:
      service: notify.pushbullet
      data:
        message: 'Aviso - O certificado expira em 10 dias' 

        
#######################################################################################################################
#  ____    ____    _         ____                                   
# / ___|  / ___|  | |       |  _ \    ___   _ __     ___  __      __
# \___ \  \___ \  | |       | |_) |  / _ \ | '_ \   / _ \ \ \ /\ / /
#  ___) |  ___) | | |___    |  _ <  |  __/ | | | | |  __/  \ V  V / 
# |____/  |____/  |_____|   |_| \_\  \___| |_| |_|  \___|   \_/\_/  
#                                                                   
#######################################################################################################################        
- alias: 'Auto Renew SSL Cert'
  trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
  action:
      service: shell_command.renew_ssl


#######################################################################################################################
#  _   _      _        _____                              _           _          
# | | | |    / \      |_   _|   ___   _ __ ___    _ __   | |   __ _  | |_    ___ 
# | |_| |   / _ \       | |    / _ \ | '_ ` _ \  | '_ \  | |  / _` | | __|  / _ \
# |  _  |  / ___ \      | |   |  __/ | | | | | | | |_) | | | | (_| | | |_  |  __/
# |_| |_| /_/   \_\     |_|    \___| |_| |_| |_| | .__/  |_|  \__,_|  \__|  \___|
#                                                |_|                             
#######################################################################################################################

- alias: switch_ha_template
  id: switch_ha_template
  trigger:
    - platform: state
      entity_id: input_select.homeassistant_template
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.homeassistant_template.state }}"

  # IF: { sun.sun goes under horizon } THEN: { set theme to night mode }
- alias: day_to_night_theme
  id: day_to_night_theme
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homeassistant_template
        option: 'darkred'

  # IF: { sun.sun is up } THEN: { set theme to day mode }
- alias: night_to_day_theme
  id: night_to_day_theme
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homeassistant_template
        option: 'darkorange'
