#===========
#=== Groups
#===========
group:

  irrigation_information:
    control: hidden
    name: Informação de Irrigação
    entities:
      - group.irrigation_weather_information
      - input_number.temperature_baseline
      - input_number.rainfall_threshold
      - sensor.last_irrigated_time
      - sensor.zone1_time_today
      - sensor.zone2_time_today

  irrigation_cycle1:
    control: hidden
    name: 'Ciclo matinal'
    entities:
      - input_boolean.cycle1_enable
      - sensor.cycle1_next_run_time
      - input_boolean.cycle1_manual_run
      - input_select.cycle1_schedule_time
      - input_select.cycle1_watering_days
      - input_number.cycle1_zone1_duration
      - input_number.cycle1_zone2_duration

  irrigation_cycle1_status:
    control: hidden
    name: 'Estado do ciclo matinal'
    entities:
      - sensor.cycle1_running
      - sensor.cycle1_zone_being_watered
      - timer.cycle1_zone_duration
      - group.cycle1_weather_settings

  irrigation_cycle2:
    control: hidden
    name: 'Ciclo noturno'
    entities:
      - input_boolean.cycle2_enable
      - sensor.cycle2_next_run_time
      - input_boolean.cycle2_manual_run
      - input_select.cycle2_schedule_time
      - input_select.cycle2_watering_days
      - input_number.cycle2_zone1_duration
      - input_number.cycle2_zone2_duration
           
  irrigation_cycle2_status:
    control: hidden
    name: 'Estado do ciclo noturno'
    entities:
      - sensor.cycle2_running
      - sensor.cycle2_zone_being_watered
      - timer.cycle2_zone_duration
      - group.cycle2_weather_settings

  irrigation_valves:
    name: 'Válvulas'
    entities:
      - switch.zone1_valve
      - switch.zone2_valve

  cycle1_weather_settings:
    control: hidden
    name: Parâmetros meteorológicos ciclo matinal
    icon: mdi:weather-partlycloudy
    entities:
    - input_boolean.cycle1_use_weather_adjustment
    - sensor.cycle1_zone1_duration_adjusted
    - sensor.cycle1_zone2_duration_adjusted
    
  cycle2_weather_settings:
    control: hidden
    name: Parâmetros meteorológicos ciclo noturno
    icon: mdi:weather-partlycloudy
    entities:
    - input_boolean.cycle2_use_weather_adjustment
    - sensor.cycle2_zone1_duration_adjusted
    - sensor.cycle2_zone2_duration_adjusted

  irrigation_weather_information:
  # Uses the Weather Underground weather sensor
    name: Histórico Meteo Info
    icon: mdi:weather-partlycloudy
#    icon: mdi:settings
    entities:
    - sensor.temp_high_2days
    - sensor.temp_high_5days

    - sensor.temp_minus0
    - sensor.temp_minus1
    - sensor.temp_minus2
    - sensor.temp_minus3
    - sensor.temp_minus4

    - sensor.rain_3days_ratio

    - sensor.rain_minus0
    - sensor.rain_minus1
    - sensor.rain_minus2
    - sensor.rain_minus3
      
#================
#=== Input_Texts
#================
input_text:
  cycle1_current_zone:
    name: Ciclo 1 zona atual

  cycle2_current_zone:
    name: Ciclo 2 zona atual


#==================
#=== Input_Selects
#==================
input_select:

  cycle1_watering_days:
    name: Ciclo matinal - dias
    options:
      - 'Daily'
      - 'Alternate'
    icon: mdi:calendar

  cycle2_watering_days:
    name: Ciclo noturno - dias
    options:
      - 'Daily'
      - 'Alternate'
    icon: mdi:calendar

  cycle1_schedule_time:
    name: Ciclo matinal - início do ciclo
    options:
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
    icon: mdi:alarm

  cycle2_schedule_time:
    name: Ciclo noturno - início do ciclo
    options:
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
      - '23:00'
    icon: mdi:alarm


#==================
#=== Input_Numbers
#==================
input_number:

  # CYCLE 1
  cycle1_zone1_duration:
    name: Duração da zona 1
    min: 0
    max: 30
    step: 1
    icon: mdi:camera-timer

  cycle1_zone2_duration:
    name: Duração da zona 2
    min: 0
    max: 30
    step: 1
    icon: mdi:camera-timer

  # CYCLE 2
  cycle2_zone1_duration:
    name: Duração da zona 1
    min: 0
    max: 30
    step: 1
    icon: mdi:camera-timer

  cycle2_zone2_duration:
    name: Duração da zona 2
    min: 0
    max: 30
    step: 1
    icon: mdi:camera-timer  

  # The temperature above or below which the duration is adjusted
  temperature_baseline:
    name: Baseline temperatura
    min: 15
    max: 25
    icon: mdi:thermometer
    unit_of_measurement: '°C'

  # How much rain is needed before the duration is reduced
  rainfall_threshold:
    name: Quantidade de chuva
    min: 5
    max: 30
    icon: mdi:weather-rainy
    unit_of_measurement: 'mm'

  # Adjusted duration times can be extreme during calculations
  # depending on weather conditions so min and max are set high
  adjusted_cycle1_zone1_duration:
    name: Ajuste duração ciclo1 / zona1
    min: -60
    max: 60

  adjusted_cycle1_zone2_duration:
    name: Ajuste duração ciclo1 / zona2
    min: -60
    max: 60

  adjusted_cycle2_zone1_duration:
    name: Ajuste duração ciclo2 / zona1
    min: -60
    max: 60

  adjusted_cycle2_zone2_duration:
    name: Ajuste duração ciclo2 / zona2
    min: -60
    max: 60

  # Temperature
  temp_minus0:
    name: Temp. hoje
    min: 0
    max: 40
    icon: mdi:thermometer

  temp_minus1:
    name: Temp. ontem
    min: 0
    max: 40
    icon: mdi:thermometer

  temp_minus2:
    name: Temp. há 2 dias
    min: 0
    max: 40
    icon: mdi:thermometer

  temp_minus3:
    name: Temp. há 3 dias
    min: 0
    max: 40
    icon: mdi:thermometer

  temp_minus4:
    name: Temp. há 4 dias
    min: 0
    max: 40
    icon: mdi:thermometer

  temp_high_2days:
    name: Média temp. 2 dias
    min: 0
    max: 40
    mode: box
    icon: mdi:thermometer

  temp_high_5days:
    name: Média temp. 5 dias
    min: 0
    max: 40
    mode: box
    icon: mdi:thermometer


  # Rainfall
  rain_minus0:
    name: Chuva hoje
    min: 0
    max: 100
    icon: mdi:weather-rainy

  rain_minus1:
    name: Chuva ontem
    min: 0
    max: 100
    icon: mdi:weather-rainy

  rain_minus2:
    name: Chuva há 2 dias
    min: 0
    max: 100
    icon: mdi:weather-rainy

  rain_minus3:
    name: Chuva há 3 dias
    min: 0
    max: 100
    icon: mdi:weather-rainy

  rain_3days_ratio:
    name: Ajuste chuva últimos 3 dias
    min: 0
    max: 500
    step: 0.01
    mode: box
    icon: mdi:weather-rainy


#===================
#=== Input_Booleans
#===================
input_boolean:

  cycle1_enable:
    name: Ativar agendamento
    icon: mdi:pipe
    
  cycle2_enable:
    name: Ativar agendamento
    icon: mdi:pipe

  cycle1_use_weather_adjustment:
    name: Utilizar ajuste METEO
    icon: mdi:weather-partlycloudy

  cycle2_use_weather_adjustment:
    name: Utilizar ajuste METEO
    icon: mdi:weather-partlycloudy

  cycle1_manual_run:
    name: Executar ciclo matinal agora
    icon: mdi:arrow-right-drop-circle

  cycle2_manual_run:
    name: Executar ciclo noturno agora
    icon: mdi:arrow-right-drop-circle

  cycle1_running:
    name: Ciclo 1 em curso

  cycle2_running:
    name: Ciclo 2 em curso


#====================
#=== Input_Datetimes
#====================
input_datetime:
  cycle1_next_run_time:
    has_date: true
    has_time: true

  cycle2_next_run_time:
    has_date: true
    has_time: true

  last_irrigated_time:
    has_date: true
    has_time: true


#===========
#=== timers
#===========
timer:
  cycle1_zone_duration:
    name: Tempo restante

  cycle2_zone_duration:
    name: Tempo restante


#============
#=== Sensors
#============
sensor:
  - platform: template
    sensors:

      cycle1_next_run_time:
        friendly_name: "Próximo agendamento"
        value_template: >
          {% if is_state('input_boolean.cycle1_enable', 'on') %}
            {{ (as_timestamp(states.input_datetime.cycle1_next_run_time.state)) | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}
        icon_template: mdi:clock-start

      cycle2_next_run_time:
        friendly_name: "Próximo agendamento"
        value_template: >
          {% if is_state('input_boolean.cycle2_enable', 'on') %}
            {{ (as_timestamp(states.input_datetime.cycle2_next_run_time.state)) | timestamp_custom("%a %d %h at %H:%M") }}
          {% else %}
            None
          {% endif %}
        icon_template: mdi:clock-start

      cycle1_running:
        friendly_name: "Ciclo matinal"
        value_template: >
          {% if is_state('input_boolean.cycle1_running', 'on') %}
            Em execução
          {% else %}
            Parado
          {% endif %}     
        icon_template: >
          {% if is_state('input_boolean.cycle1_running', 'on') %}
            mdi:run
          {% else %}
            mdi:human-handsdown
          {% endif %}     
          
      cycle2_running:
        friendly_name: "Ciclo noturno"
        value_template: >
          {% if is_state('input_boolean.cycle2_running', 'on') %}
            Em execução
          {% else %}
            Parado
          {% endif %}     
        icon_template: >
          {% if is_state('input_boolean.cycle2_running', 'on') %}
            mdi:run
          {% else %}
            mdi:human-handsdown
          {% endif %}     

      cycle1_zone_being_watered:
        friendly_name: "Zona a ser regada"
        value_template: "{{ states('input_text.cycle1_current_zone') }}"     
        icon_template: mdi:square-inc
        
      cycle2_zone_being_watered:
        friendly_name: "Zona a ser regada"
        value_template: "{{ states('input_text.cycle2_current_zone') }}"     
        icon_template: mdi:square-inc

      last_irrigated_time:
        friendly_name: "Conclusão do último ciclo"
        value_template: >
          {{ (as_timestamp(states.input_datetime.last_irrigated_time.state)) | timestamp_custom("%a %d %h at %H:%M") }}
        icon_template: mdi:update
        
      # Zone Times - templated on history_stats sensors
      zone1_time_today:
        friendly_name: Total de tempo na zona1 hoje
        value_template: >
          {% set duration = states('sensor.zone1_time') %}
          {{ (float(duration) * 60) | round }}
        unit_of_measurement: minutes
        icon_template: mdi:water

      zone2_time_today:
        friendly_name: Total de tempo na zona2 hoje
        value_template: >
          {% set duration = states('sensor.zone2_time') %}
          {{ (float(duration) * 60) | round }}
        unit_of_measurement: minutes
        icon_template: mdi:water

      cycle1_zone1_duration_adjusted:
        friendly_name: "Ajuste na duração da zona 1"
        value_template: "{{ states('input_number.adjusted_cycle1_zone1_duration') | int }}"     
        icon_template: mdi:camera-timer

      cycle1_zone2_duration_adjusted:
        friendly_name: "Ajuste na duração da zona 2"
        value_template: "{{ states('input_number.adjusted_cycle1_zone2_duration') | int }}"     
        icon_template: mdi:camera-timer

      cycle2_zone1_duration_adjusted:
        friendly_name: "Ajuste na duração da zona 1"
        value_template: "{{ states('input_number.adjusted_cycle2_zone1_duration') | int }}"     
        icon_template: mdi:camera-timer

      cycle2_zone2_duration_adjusted:
        friendly_name: "Ajuste na duração da zona 2"
        value_template: "{{ states('input_number.adjusted_cycle2_zone2_duration') | int }}"     
        icon_template: mdi:camera-timer

      # Weather information sensors
      # Temperature
      temp_minus0:
        friendly_name: Temp. hoje
        value_template: "{{ states('input_number.temp_minus0') | int }}"     
        icon_template: mdi:thermometer

      temp_minus1:
        friendly_name: Temp. ontem
        value_template: "{{ states('input_number.temp_minus1') | int }}"     
        icon_template: mdi:thermometer

      temp_minus2:
        friendly_name: Temp. há 2 dias
        value_template: "{{ states('input_number.temp_minus2') | int }}"     
        icon_template: mdi:thermometer

      temp_minus3:
        friendly_name: Temp. há 3 dias
        value_template: "{{ states('input_number.temp_minus3') | int }}"     
        icon_template: mdi:thermometer

      temp_minus4:
        friendly_name: Temp. há 4 dias
        value_template: "{{ states('input_number.temp_minus4') | int }}"     
        icon_template: mdi:thermometer

      temp_high_2days:
        friendly_name: Média temp. 2 dias
        value_template: "{{ states('input_number.temp_high_2days') | int }}"     
        icon_template: mdi:thermometer

      temp_high_5days:
        friendly_name: Média temp. 5 dias
        value_template: "{{ states('input_number.temp_high_5days') | int }}"     
        icon_template: mdi:thermometer


      # Rainfall
      rain_minus0:
        friendly_name: Chuva hoje
        value_template: "{{ states('input_number.rain_minus0') | int }}"     
        icon_template: mdi:weather-rainy

      rain_minus1:
        friendly_name: Chuva ontem
        value_template: "{{ states('input_number.rain_minus1') | int }}"     
        icon_template: mdi:weather-rainy

      rain_minus2:
        friendly_name: Chuva há 2 dias
        value_template: "{{ states('input_number.rain_minus2') | int }}"     
        icon_template: mdi:weather-rainy

      rain_minus3:
        friendly_name: Chuva há 3 dias
        value_template: "{{ states('input_number.rain_minus3') | int }}"     
        icon_template: mdi:weather-rainy

      rain_3days_ratio:
        friendly_name: Ajuste chuva últimos 3 dias
        value_template: "{{ states('input_number.rain_3days_ratio') | int }}"     
        icon_template: mdi:weather-rainy


  # History sensors
  # Zone Times
  - platform: history_stats
    name: zone1_time
    entity_id: switch.zone1_valve
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: zone2_time
    entity_id: switch.zone2_valve
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

#=============
#=== Switches
#=============
switch:

  # sonoff (4ch)
  # Zone 1
  - platform: mqtt
    name: "Zone1 valve"
    state_topic: "stat/rega/POWER1"
    command_topic: "cmnd/rega/power1"
    availability_topic: "tele/rega/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  # Zone 2
  - platform: mqtt
    name: "Zone2 valve"
    state_topic: "stat/rega/POWER2"
    command_topic: "cmnd/rega/power2"
    availability_topic: "tele/rega/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true