
#######################################################################################################################      
#      ___         ___           ___           ___           ___           ___           ___     
#     /  /\       /  /\         /  /\         /  /\         /  /\         /  /\         /  /\    
#    /  /:/_     /  /::\       /  /:/_       /  /:/_       /  /::|       /  /:/_       /  /::\   
#   /  /:/ /\   /  /:/\:\     /  /:/ /\     /  /:/ /\     /  /:/:|      /  /:/ /\     /  /:/\:\  
#  /  /:/ /:/  /  /:/~/:/    /  /:/ /:/_   /  /:/ /:/_   /  /:/|:|__   /  /:/ /:/_   /  /:/~/:/  
# /__/:/ /:/  /__/:/ /:/___ /__/:/ /:/ /\ /__/:/ /:/ /\ /__/:/ |:| /\ /__/:/ /:/ /\ /__/:/ /:/___
# \  \:\/:/   \  \:\/:::::/ \  \:\/:/ /:/ \  \:\/:/ /:/ \__\/  |:|/:/ \  \:\/:/ /:/ \  \:\/:::::/
#  \  \::/     \  \::/~~~~   \  \::/ /:/   \  \::/ /:/      |  |:/:/   \  \::/ /:/   \  \::/~~~~ 
#   \  \:\      \  \:\        \  \:\/:/     \  \:\/:/       |  |::/     \  \:\/:/     \  \:\     
#    \  \:\      \  \:\        \  \::/       \  \::/        |  |:/       \  \::/       \  \:\    
#     \__\/       \__\/         \__\/         \__\/         |__|/         \__\/         \__\/    
#######################################################################################################################

#homeassistant:
##   ____                 _                         _              
##  / ___|  _   _   ___  | |_    ___    _ __ ___   (_)  ____   ___ 
## | |     | | | | / __| | __|  / _ \  | '_ ` _ \  | | |_  /  / _ \
## | |___  | |_| | \__ \ | |_  | (_) | | | | | | | | |  / /  |  __/
##  \____|  \__,_| |___/  \__|  \___/  |_| |_| |_| |_| /___|  \___|
#
#  customize:
#    light.quarto_margarida_geral:
#      custom_ui_state_card: state-card-custom-ui
#      show_last_changed: true
#      friendly_name: "Geral"
#    light.quarto_margarida_geral_simples:
#      custom_ui_state_card: state-card-custom-ui
#      show_last_changed: true
#      friendly_name: "Geral Simples"
#    light.quarto_margarida_candeeiro_aviao:
#      custom_ui_state_card: state-card-custom-ui
#      show_last_changed: true
#      friendly_name: "Avião"
#    light.quarto_margarida_wc:
#      custom_ui_state_card: state-card-custom-ui
#      show_last_changed: true
#      friendly_name: "WC"

#  ____               _   _            _     
# / ___|  __      __ (_) | |_    ___  | |__  
# \___ \  \ \ /\ / / | | | __|  / __| | '_ \ 
#  ___) |  \ V  V /  | | | |_  | (__  | | | |
# |____/    \_/\_/   |_|  \__|  \___| |_| |_|

#  ____                                      
# / ___|    ___   _ __    ___    ___    _ __ 
# \___ \   / _ \ | '_ \  / __|  / _ \  | '__|
#  ___) | |  __/ | | | | \__ \ | (_) | | |   
# |____/   \___| |_| |_| |___/  \___/  |_|     

#  _       _           _       _         
# | |     (_)   __ _  | |__   | |_   ___ 
# | |     | |  / _` | | '_ \  | __| / __|
# | |___  | | | (_| | | | | | | |_  \__ \
# |_____| |_|  \__, | |_| |_|  \__| |___/
#              |___/                           
  light:
    - platform: mqtt
      name: "Quarto Margarida Geral"
      command_topic: "cmnd/luzquartomargaridaduplo/power1" 
      state_topic: "stat/luzquartomargaridaduplo/POWER1" 
      qos: 1 
      payload_on: "ON" 
      payload_off: "OFF" 
      retain: false
      availability_topic: "tele/luzquartomargaridaduplo/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"    
      
    - platform: mqtt
      name: "Quarto Margarida Geral Simples"
      hidden: true
      command_topic: "cmnd/luzquartomargaridasimples/power" 
      state_topic: "stat/luzquartomargaridasimples/POWER" 
      availability_topic: "tele/luzquartomargaridasimples/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1 
      payload_on: "ON" 
      payload_off: "OFF" 
      retain: false    
                                                                                     
    - platform: mqtt
      name: "Quarto Margarida Candeeiro Avião"
      command_topic: "cmnd/luzquartomargaridaduplo/power2" 
      state_topic: "stat/luzquartomargaridaduplo/POWER2" 
      qos: 1 
      payload_on: "ON" 
      payload_off: "OFF" 
      retain: false
      availability_topic: "tele/luzquartomargaridaduplo/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
  
    - platform: mqtt
      name: "Quarto Margarida WC"
      command_topic: "cmnd/luzquartomargaridawc/power" 
      state_topic: "stat/luzquartomargaridawc/POWER" 
      qos: 1 
      payload_on: "ON" 
      payload_off: "OFF" 
      retain: false
      availability_topic: "tele/luzquartomargaridawc/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

      
#     _              _                                 _     _                 
#    / \     _   _  | |_    ___    _ __ ___     __ _  | |_  (_)   ___    _ __  
#   / _ \   | | | | | __|  / _ \  | '_ ` _ \   / _` | | __| | |  / _ \  | '_ \ 
#  / ___ \  | |_| | | |_  | (_) | | | | | | | | (_| | | |_  | | | (_) | | | | |
# /_/   \_\  \__,_|  \__|  \___/  |_| |_| |_|  \__,_|  \__| |_|  \___/  |_| |_|
  automation:
    - id: quarto_margarida_duplo
      alias: 'Quarto Margarida Duplo'
      trigger:
        - platform: state
          entity_id: light.quarto_margarida_geral
      action:
        - service_template: >
              {% if is_state('light.quarto_margarida_geral', 'on') %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
    
          data:
            entity_id: light.quarto_margarida_geral_simples
            
    - id: quarto_margarida_simples
      alias: 'Quarto Margarida Simples'
      trigger:
        - platform: state
          entity_id: light.quarto_margarida_geral_simples
      action:
        - service_template: >
              {% if is_state('light.quarto_margarida_geral_simples', 'on') %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}

          data:
            entity_id: light.quarto_margarida_geral

#   ____                                
#  / ___|  _ __    ___    _   _   _ __  
# | |  _  | '__|  / _ \  | | | | | '_ \ 
# | |_| | | |    | (_) | | |_| | | |_) |
#  \____| |_|     \___/   \__,_| | .__/ 
#                                |_|              
  group:
    luzes_quartomargarida:
        name: Quarto da Margarida
        view: no
        entities:
            - light.quarto_margarida_geral
            - light.quarto_margarida_candeeiro_aviao
            - light.quarto_margarida_wc
            